workspace:
  base: /go
  path: src/github.com/arduino/arduino-cli

pipeline:
  build:
    image: golang:1.10
    environment:
      - DEP_RELEASE_TAG=v0.5.0
    commands:
      - go generate
      # Tools install dep, golangci-lint
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      # Check the dependency, the -skip-lock is useful because the version are not fixed but depends from the branch master of the libraries so they change very often
      - dep check
      # Check if the code is formatted
      -  $(exit $(go fmt ./... | wc -l))
      # Build
      - go build
      - go test -timeout 20m -v ./... -race
      - golangci-lint run
    secrets: [TEST_USERNAME, TEST_PASSWORD]
